### ISSUE TITLE
Output index of column/variable

### ISSUE THREAD

**Issue by Kudusch** [NickCH-K/vtable#1]
It would be nice to see the index of the column/variable in the generated output. This is basically already in place with:

`vt$order <- 1:nrow(vt)`

Do you have any plans for this or are you taking pull requests? This could also be an optional output with something like 

`@param index Set to TRUE to include variable indices in the variable table. Defaults to FALSE.`

Thanks for the package btw :)

**Comment by NickCH-K** [comment]
This is now included in v0.2.0! Thanks for the suggestion.

**Comment by NickCH-K** [comment]
Oh, wait, I misunderstood the request. I will include this.
