### ISSUE TITLE
Allow Pctl. 50 in the vtable::st()

### ISSUE THREAD

**Issue by gbganalyst** [NickCH-K/vtable#10]
Thank you @NickCH-K for adding some cool functions in the vtable package.

Please I want to suggest that vtable::st() should also include Pctl. 50 which equals the median.

I just visited the documentation of pandas.DataFrame.describe() at https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html and it includes the 50th percentile.

**Comment by NickCH-K** [comment]
I was running into an issue with there being too many columns (so everything was getting squished) and so took the median out of the default. It can be added back in with the `summ` option, though, e.g. `summ = c('notNA(x)','mean(x)','sd(x)','min(x)','pctile(x)[25]','median(x)','pctile(x)[75]','max(x)')

**Comment by gbganalyst** [comment]
I think it will look nice if we include it by default. Also it would be good if we shorten Pctl. 50 to P50, Pctl. 75 to P75 and Std. Dev to std. That would then allow for a column for the median.

**Comment by DataScienceNigeria** [comment]
For example, I am currently doing an analysis that involves the age of patients in the clinic. There was an error in the age but I can easily go with median instead of the mean. So I encourage the median to be there by default
![medical work](https://user-images.githubusercontent.com/40419106/95001511-8e0dde80-05c2-11eb-8e30-f8b766b7a9b1.png)
.

**Comment by NickCH-K** [comment]
I'll think about it. For now, at least, you can still get the median in there using the `summ` argument.

**Comment by NickCH-K** [comment]
I haven't added it as a default, but `add.median` has now been added as an option which will very easily add the median.
