### ISSUE TITLE
Suggestion: add "number of nonzero observations" column option to vtable::sumtable

### ISSUE THREAD

**Issue by daaronr** [NickCH-K/vtable#13]
Loving this tool, thanks for building it!

I often want to add 'number of nonzero obs' (not just 'number nonmissing') to the summary tables. Perhaps there is a way of doing it but I can't figure it out.

**Comment by NickCH-K** [comment]
Interesting! This can definitely be done by modifying the `summ` argument with something like `sum(x != 0)`, but I can see the potential value in adding it as an easier option. I'll think about it.

**Comment by daaronr** [comment]
Thank you `'sum(x > 0)'`  works great. I am not a brilliant R coder, so I sometimes don't know the "raw" way of doing things

**Comment by NickCH-K** [comment]
Great! Do keep in mind `sum(x>0)` will only work if `x` is never negative. If `x` ever takes negative values you'll want `sum(x != 0)`.
