### ISSUE TITLE
Showing many numeric labels

### ISSUE THREAD

**Issue by johnhenrypezzuto** [NickCH-K/vtable#19]
I have a labeled dataset:

``` r
library(tidyverse)
library(haven)
df = structure(list(social_ideo = structure(c(2, -3, -3, 0, -3, -2, 
                                              -2, -3, -2, -3), 
                                            label = "In terms of social and cultural issues, how liberal or conservative are your views?", 
                                            format.spss = "F40.0", 
                                            display_width = 5L, 
                                            labels = c(`Extremely liberal` = -3,
                                                       Liberal = -2, 
                                                       `Slightly Liberal` = -1, 
                                                       Neither = 0, 
                                                       `Slightly Conservative` = 1,
                                                       Conservative = 2, 
                                                       `Extremely Conservative` = 3), 
                                            class = c("haven_labelled",
                                                      "vctrs_vctr", "double"))), 
               row.names = c(NA, -10L), 
               class = c("tbl_df",
                         "tbl", "data.frame"))

df
#> # A tibble: 10 × 1
#>    social_ideo
#>     <hvn_lbll>
#>  1           2
#>  2          -3
#>  3          -3
#>  4           0
#>  5          -3
#>  6          -2
#>  7          -2
#>  8          -3
#>  9          -2
#> 10          -3
```

When I `vtable(df, factor.limit = 0)` I'd like to see the value labels:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/31427520/168863487-d24a2f17-e744-4b8b-88e3-21da3d24bab2.png">

Is there a way to include all the labels for labeled data that are not factors? `labeltable` produces the correct output.

(vtable v. 1.3.3)

**Comment by johnhenrypezzuto** [comment]
No, in my real data, I read in the data from an SPSS file. I just used `structure` to create the reproducible example. I can upload a small SPSS file too if helpful.

**Comment by NickCH-K** [comment]
Yeah that would help

On May 17, 2022 10:12 AM, John-Henry Pezzuto ***@***.***> wrote:

No, in my real data, I read in the data from an SPSS file. I just used structure to create the reproducible example. I can upload a small SPSS file too if helpful.

**Comment by johnhenrypezzuto** [comment]
[df.sav.zip](https://github.com/NickCH-K/vtable/files/8710367/df.sav.zip)

**Comment by johnhenrypezzuto** [comment]
[df.sav.zip](https://github.com/NickCH-K/vtable/files/8710374/df.sav.zip)

**Comment by NickCH-K** [comment]
Alright I think I've fixed it; try installing the dev version with `remotes::install_github('NickCH-K/vtable')` (after perhaps installing the remotes package using `install.packages('remotes')`

**Comment by johnhenrypezzuto** [comment]
Thanks that's working for me! 

Moving beyond the scope of the original issue I noticed that if I use `haven_labelled` column, the summary stats aren't coming up:

```r
haven::read_spss("df.sav") %>% 
  vtable::vtable(., 
         out = "browser",  
         summ=c("mean(x)",
                "sd(x)"), 
         missing = T
  )
```

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/31427520/169030149-ea767888-5917-41cf-ba74-7d67a8268136.png">


Similarly (moving beyond the data I shared), I noticed that `POSIXct` type column, the summary stats are still being calculated when I don't think they should be: 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/31427520/169030503-9287a391-4cb1-4452-a67a-e0428faafc20.png">

**Comment by NickCH-K** [comment]
Oops, sorry for the slow response, the notification email got buried.

For the `haven_labelled` column that's the intended behavior. In typical use, variables with labelled values are factors and in fact are converted to `factor` for processing in `vtable`. So it gets the treatment of a factor variable, i.e. no summary stats.

As for dates, I went back and forth on whether to report summary stats when setting up the date code. There are a fair number of cases where you might want to see descriptives for the numeric conversion of a date/time (granted, more often with date-only variables than datetime). There are also a fair number of cases where you wouldn't. I ended up letting it convert to numeric.

**Comment by NickCH-K** [comment]
This did inspire me to do some work on dates in `vtable`'s `summ` option. Try downloading the newest version from GitHub. Dates will both maintain class after being passed through a function for `summ` (so `mean(x)` will produce a mean date, not a mean number), and also `lush = TRUE` will use functions `median(x)` instead of `mean(x)` and `sd(x)` for dates now. Planning to send to CRAN in a week or two, so let me know if it works for you.

**Comment by johnhenrypezzuto** [comment]
Works great for me so far! Thank you!
