### ISSUE TITLE
Issue with group.test.opts

### ISSUE THREAD

**Issue by yjin-chae** [NickCH-K/vtable#20]
https://github.com/NickCH-K/vtable/blob/488e96cddaa4c2df8d71334d973fbaca6d8828a0/R/sumtable.R#L719

Thank you for this great package. I've been using this for many many papers.

Recently I found that the independence test being performed across subgroups cannot use different significance levels other than the default, .10, .05, and .0.01; it turns out the line I reference above contains an error and I think the line is supposed to be like:

`star.markers <- group.test.opts[['star.markers']]`

rather than:

`star.cutoffs <- group.test.opts[['star.markers']]`

I customized the function accordingly and could produce summary statistics with tests using different significance levels. It would be great if this change could be made on the package. Thank you so much.

Best,
YJ

**Comment by NickCH-K** [comment]
Thank you very much, and right you are! I've pushed a fix to the GitHub version, and am planning to upload to CRAN in a few weeks.
