### ISSUE TITLE
Unused argument `numformat`

### ISSUE THREAD

**Issue by MadsLang** [NickCH-K/vtable#24]
I get an error when I try to run the example for the argument `numformat` from the vignette here: https://cran.r-project.org/web/packages/vtable/vignettes/sumtable.html

This code: 
```
library("vtable")
vtable::st(iris, numformat = c('|cm', 'Sepal.Width' = 'percent'))
```

The error message: 
```
Error in vtable::st(iris, numformat = c("|cm", Sepal.Width = "percent")) : 
  unused argument (numformat = c("|cm", Sepal.Width = "percent"))
Execution halted
```

Is this argument no longer supported, or what could be the issue?

**Comment by NickCH-K** [comment]
That's odd, it works for me (and worked when the vignette compiled!)

The `numformat` option is actually new, added just a few versions ago. Is your version perhaps not updated? Try updating to the newest version of vtable and give it a go again.

**Comment by MadsLang** [comment]
Yes - that was the issue 👍  Thank for the quick reply
