### ISSUE TITLE
Always return a data frame in sumtable / st

### ISSUE THREAD

**Issue by JGWestie** [NickCH-K/vtable#25]
Hi, great package!

I am curious as to why the `sumtable` /  `st` functions do not return a data frame by default, even if the user was to specify say `out = "viewer"`? Currently the function only returns a data frame if the user specifies `out = "return"`, but I would ideally like to be able to look / wrangle the data frame data once I've run the function, but having it appear in the Viewer window in RStudio is nicer than looking at the data frame using `base::View()`; it's quicker to look up the information of interest to me.

Currently I think I would have to call the function twice, once with  `out = "return"` and once with  `out = "viewer"` to be able to get the output available to wrangle and to visualise in the Viewer window, which seems unnecessarily inefficient?

I think this change should be fairly easy if you end the function with an extra return (the script currently doesn't return anything after looking within each  `if` block? Alternatively perhaps supporting multiple options for the  `out` argument could work well, though that might be a bit more time consuming?

Thanks,

Jack

**Comment by NickCH-K** [comment]
Glad you like the package!

The primary use case for the package is "looking-at" as opposed to "wrangling-with" after the fact, and defaults are designed with that in mind. For example, even with `out = 'return'` output, numbers are often formatted as text, and some `sumtable` output uses two rows of column headers, which stymies data wrangling. As such, returning a `data.frame` in addition to the Viewer tab output is not desired as this would often be redundant, and would actively get in the way if you were, say, including your results in an RMarkdown/Quarto doc, which I think is more common a use case than wrangling with the output after it's created.. 

Allowing a vector of `out` inputs and returning all of them wouldn't be too difficult to implement, but I'm not sure this is a common enough use case to qualify (and doing `out = 'return'` followed by `out = 'viewer'` isn't that difficult, especially compared to the alternative of having to read the docs to figure out how to do both in one line).

**Comment by JGWestie** [comment]
Thanks for the swift reply! Not a problem, doesn’t sound like if’s beneficial to enough people to implement the above changes then. I can live with calling the function multiple times. The function is fast enough for this not to be a problem.
