### ISSUE TITLE
st() fails for pdf format in quarto doc due to missing escape of %

### ISSUE THREAD

**Issue by agjest** [NickCH-K/vtable#26]
Minimal example Quarto doc:
---
title: "vtable bug"
format: pdf
---

```{r}
#| label: setup
library(vtable)
```

```{r}
iris |> st()
```

Fails since % in group percentages is not escaped.

st(out = "latex") returns latex code with proper escaping of %

**Comment by NickCH-K** [comment]
Odd, this used to work. I wonder if `kable()` has changed. I'll look into it. Thank you!

**Comment by NickCH-K** [comment]
Fixed with dba4a22ce02532809f8917914995fb9951600c1c , give that a shot. Will push to CRAN in a few wekes.
