### ISSUE TITLE
sumtable() in R gives irreproducible error

### ISSUE THREAD

**Issue by JonatHorowitz** [NickCH-K/vtable#27]
I am sorry if this isn't the right place to ask this question, but I've been getting a very strange error message with factor.numeric that my colleague is not getting. I'm not sure if this is a bug or if I just don't understand how to use sumtable properly.

https://stackoverflow.com/questions/77310342/sumtable-in-r-gives-irreproducible-error

Thanks so much for the great package--it's fantastic.

**Comment by NickCH-K** [comment]
Hmm, this appears to be something odd (a change?) in the way that tibbles respond to a certain variable-selection syntax. For now the problem can be resolved by using `as.data.frame(WVS2)`, but I will fix this.

**Comment by JonatHorowitz** [comment]
Thank you for your prompt response!

**Comment by NickCH-K** [comment]
Fixed this last year but forgot to ever close the issue.
