### ISSUE TITLE
option to show first X unique variables of character variables?

### ISSUE THREAD

**Issue by rmflight** [NickCH-K/vtable#4]
I don't use factors very often for `character` variables, so it would be great if `vtable` did for `characters` what it is already doing for `factors`, as in show some of the values that the `character` columns take.

Not sure how much work that would take, but would entertain making a pull request for this feature when I have some more time.

**Comment by NickCH-K** [comment]
Interesting! I like that idea. Shouldn't be too difficult - I think it would probably work to just convert the characters to factors after getting their class and before getting their values. I have some other troubleshooting to do this weekend so I might just be able to add it then.

**Comment by rmflight** [comment]
That would be the approach I would take. Thanks!

**Comment by NickCH-K** [comment]
This is now in the GitHub version! See the char.values option; set to TRUE for all character variables, or c('var1','var2','var3') to just do some of them. Number displayed is set the same as for factors. Thank you!

**Comment by rmflight** [comment]
Looking forward to trying it out, thank you so much!
