### ISSUE TITLE
Rebuild home page

### ISSUE THREAD

**Issue by grantmcdermott** [NickCH-K/vtable#8]
Hey Nick,

Just noticed that your README.md file is outdated and still advises users to install **pmdplyr** instead of **vtable**. This obviously carries through to the pkgdown site too. See [here](https://nickch-k.github.io/vtable/index.html#installation).

I can see that the underlying Rmd file is [correct](https://github.com/NickCH-K/vtable/blob/master/README.Rmd#L38), so you should be able to fix quickly with `pkgdown::build_home().`

P.S. My last (very minor) suggestion would be that users should install the dev version using `remotes::install_github("NickCH-K/vtable")`. You may know though this already, but **remotes** is intended as a lightweight alternative to **devtools** that doesn't come with all the bloat needed for package building and maintenance.

**Comment by NickCH-K** [comment]
Oh strange - I've been running build_site() before pushing every time, but there was some sort of permissions problem that wasn't letting the home page update. Fixed with 01a95c94eadcb9e582a66e1624ce0a3266547d7b

Thanks!
