### ISSUE TITLE
LaTeX error without explicitly loading kableExtra

### ISSUE THREAD

**Issue by grantmcdermott** [NickCH-K/vtable#9]
Another minor(ish) issue:

When exporting to pdf_document in a R Markdown document, you need need to load **kableExtra** otherwise `vtable::st()` won't always load the necessary LaTeX packages. Example:

```
---
output: 
  pdf_document:
    keep_tex:  true
---

```{r airq}
# library(kableExtra)
library(vtable)
st(iris, group = 'Species', group.long = TRUE)
```{}
```

The above fails because of an `! Undefined control sequence (l.120 \toprule)` error. You can see the problem with the intermediate Tex file.

In contrast, the below works because **kableExtra** now loads all the necessary packages like booktabs, longtable, etc. Again see the intermediate TeX file.

```
---
output: 
  pdf_document:
    keep_tex:  true
---

```{r airq}
library(kableExtra) ## uncomment!
library(vtable)
st(iris, group = 'Species', group.long = TRUE)
```{}
```

You may just want to make users aware of this if they are using R Markdown. Another alternative ofc is to have **kableExtra** automatically load as a dependency upon calling `library(vtable)`.

**Comment by NickCH-K** [comment]
Hmm, shoot. The right call here is probably to move knitr and kableExtra from Suggests to Imports. This wouldn't require it to go to Depends would it?

I'm pretty sure adding `library(kableExtra)` inside the function when it's needed is very much frowned upon

**Comment by grantmcdermott** [comment]
Yeah, I'd suggest *at least* a move to "Imports" although that will only install it, rather than attaching at load time. The latter would require that you move it up another level to "Depends"... which TBH is probably what I'd do in this situation. Up to you though! http://r-pkgs.had.co.nz/namespace.html#namespace

**Comment by NickCH-K** [comment]
Bah and humbug. I dislike the idea of the least-necessary package being the only thing in Depends, but I dislike the user having to manually load it even more. Fixed in 687c2457bc48e35dc784b69db53e93896b01937d

**Comment by grantmcdermott** [comment]
<sad firework>

Thanks Nick. Really liking this new `st()` functionality btw. The whole package is v. cool.

**Comment by NickCH-K** [comment]
Thanks! Glad you like it.
